// Mocks generated by Mockito 5.3.0 from annotations
// in flutter_tdd/test/features/number_trivia/domain/usecases/get_random_number_trivia_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;

import 'get_random_number_trivia_test.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [NumberTriviaRepositoryTest].
///
/// See the documentation for Mockito's code generation for more information.
class MockNumberTriviaRepositoryTest extends _i1.Mock
    implements _i2.NumberTriviaRepositoryTest {
  MockNumberTriviaRepositoryTest() {
    _i1.throwOnMissingStub(this);
  }
}
